name: Releases

on:
  release:
    types:
      - published

env:
  IMAGE_NAME: theknarf/hello-world
  DOCKERHUB_USERNAME: theknarf

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log into registry
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u $DOCKERHUB_USERNAME --password-stdin

      - name: Build Docker image
        run: |
          docker buildx build . \
          --push \
          --platform linux/arm/v7,linux/arm64/v8,linux/amd64 \
          --tag "$IMAGE_NAME:latest" \
          --tag "$IMAGE_NAME:${{ github.event.release.tag_name}}"

# This action does not yet work with dockerhub personal access token
# Issue: https://github.com/peter-evans/dockerhub-description/issues/10
#      - name: Docker Hub Description
#        uses: peter-evans/dockerhub-description@v2
#        with:
#          username: $DOCKERHUB_USERNAME
#          password: ${{ secrets.DOCKERHUB_PASSWORD }}
#          repository: $IMAGE_NAME
#          readme-filepath: ./Readme.md
